brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
brokerRole = SYNC_MASTER
flushDiskType = ASYNC_FLUSH
deleteWhen = 04
fileReservedTime = 48
storePathRootDir = /home/rocketmq/store
namesrvAddr = namesrv:9876
brokerIP1 = 127.0.0.1
messageStoreType = ROCKSDB
enableLiteTopic = true
liteTopicMaxQueueNum = 1000000
grpcServerPort = 8081
